### ISSUE TITLE
Day 1: "Congratulations on completing your first session!..." message is shown twice

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/factorial-design-breathing-study#17]
Factor Settings: Slow, Standard, Hide HR, Show EmoPic, Hide Audio. Performance

After completing my second 18-minute session on Day 1, I received the "Congratulations on completing your first session!..." screen again.

**Comment by noah10** [comment]
Looking at the sqlite database history I see that both the first and second sessions were correctly recorded as >= 18 minutes long and being in stage 2. Working hypothesis: emWave hadn't yet written the second session when the StageComponent grabbed all of the stage 2 sessions. Maybe we need to give it more than 500ms?

**Comment by juliana-20** [comment]
I have also received the same message after completing the 18-minute session twice. Do you think that it is related to completing one session vs. two sessions a day? These two sessions were completed in one day, on the same day as baseline.

**Comment by choipaul92** [comment]
Update: After completing my first 18-minute session on Day 2, I received this message again.

**Comment by noah10** [comment]
This turned out to be a stupid bug: I used <= when I should have used < . It should be fixed in v1.0.1.

**Comment by choipaul92** [comment]
Update: I am still seeing this message. I am on Day 2, 2nd session and on 1.0.1 version of the app.

**Comment by shaakhini** [comment]
I am also seeing this message. I am on Day 1, 2nd session and on 1.0.1 version of the app

**Comment by juliana-20** [comment]
Update - This message is shown after 2nd session on Day 2 with the 1.0.1 version of the app.

**Comment by noah10** [comment]
This turned out to be caused by two bugs. The second is fixed in 1.0.2 - hopefully that's the last one!

**Comment by choipaul92** [comment]
Ver: 1.0.5

The app does not repeat the message of "Congratulations on completing your first..." after the 2nd session on Day 1
